development: &development
  adapter: postgresql
  encoding: unicode
  database: awesome_pages_development
  pool: 100
  username: leonid
  password: 11111
  host: localhost
  min_messages: WARNING
  insert_returning: false

test:
  <<: *development
  database: awesome_pages_test

production:
  <<: *development
  database: awesome_pages_production  
